# Generated by Django 4.0 on 2021-12-19 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(blank=True, default=0, verbose_name='X координата')),
                ('y', models.IntegerField(blank=True, default=0, verbose_name='Y координата')),
                ('type_node', models.CharField(max_length=255, verbose_name='Тип')),
                ('label', models.CharField(max_length=255, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Ячейка',
                'verbose_name_plural': 'Ячейки',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_links', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_links', to='api.node', verbose_name='From')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolinks', to='api.node', verbose_name='To')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
    ]
